# Generated by Django 4.1.3 on 2022-11-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
