# Generated by Django 4.1.3 on 2022-11-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Report',
        ),
    ]
