# Generated by Django 4.1.3 on 2022-11-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_sales_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='sales_dt',
            new_name='date',
        ),
    ]
