# Generated by Django 4.1.3 on 2022-11-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_sales_dt_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
