# Generated by Django 4.1.3 on 2022-11-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_report_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='turnover',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
