# Generated by Django 4.1.3 on 2022-11-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sellingtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellingType',
            new_name='ReportType',
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.reporttype'),
        ),
    ]
