# Generated by Django 4.1.3 on 2022-11-12 09:21

from django.db import migrations


def fill_report_type(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ReportType = apps.get_model('sales', 'ReportType')
    Report = apps.get_model('sales', 'Report')
    for report in Report.objects.all():
        report_type, _ = ReportType.objects.get_or_create(name=report.selling_type)
        report.report_type = report_type
        report.save()



class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_rename_sellingtype_reporttype_report_report_type'),
    ]

    operations = [
        migrations.RunPython(fill_report_type)
    ]
