# Generated by Django 4.1.3 on 2022-11-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20221112_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='selling_type',
        ),
    ]
